### ISSUE TITLE
Spell check API not returning any response as expected

### ISSUE THREAD

**Issue by AnupAntony** [montanaflynn/Spellcheck-API#1]
Hi,

I have been trying to use spell check API by using the below end point.

https://montanaflynn-spellcheck.p.mashape.com/check/

I am not getting any suggestions / corrections for the misspelled words as response. Whatever text I am passing, its returning the same text. Could you please help on this?

Thanks, Anup.

**Comment by ssanders** [comment]
:+1: Likewise.

**Comment by montanaflynn** [comment]
Hey guys, I ported the project to node.js and it's back up and running as expected now.
